# Generated by Django 2.2.2 on 2019-06-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'day',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'dish',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'order',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('day', models.ManyToManyField(related_name='days', to='kitchen.Day')),
            ],
            options={
                'verbose_name': 'week',
            },
        ),
        migrations.CreateModel(
            name='OrdersTransit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_half', models.BooleanField(default=False)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Dish')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(related_name='orders', through='kitchen.OrdersTransit', to='kitchen.Dish'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Week'),
        ),
        migrations.AddField(
            model_name='day',
            name='dish',
            field=models.ManyToManyField(related_name='dishes', to='kitchen.Dish'),
        ),
    ]
