# Generated by Django 2.2.2 on 2019-06-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_auto_20190615_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstransit',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
