# Generated by Django 2.2.2 on 2019-06-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_auto_20190615_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='week',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ManyToManyField(related_name='weeks', to='kitchen.Week'),
        ),
        migrations.AddField(
            model_name='dish',
            name='day',
            field=models.ManyToManyField(related_name='days', to='kitchen.Day'),
        ),
    ]
