# Generated by Django 2.2.2 on 2019-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_auto_20190615_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='week',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='dish',
            field=models.ManyToManyField(related_name='days', to='kitchen.Dish'),
        ),
        migrations.AddField(
            model_name='week',
            name='day',
            field=models.ManyToManyField(related_name='week', to='kitchen.Day'),
        ),
    ]
