# Generated by Django 2.2.2 on 2019-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_auto_20190615_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='slug',
            field=models.SlugField(default='dsa-1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(default='dfsda-1', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='slug',
            field=models.SlugField(default='jghf-12', max_length=200),
            preserve_default=False,
        ),
    ]
