# Generated by Django 2.2.2 on 2019-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_auto_20190615_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='dish',
            field=models.ManyToManyField(related_name='dishes', to='kitchen.Dish'),
        ),
    ]
