# Generated by Django 2.2.2 on 2019-07-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_auto_20190701_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_half',
            field=models.BooleanField(default=False),
        ),
    ]
